version: "2"

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
  pgadmin:
    image: meedan/pgadmin
    container_name: pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    logging:
      driver: "none"
  rest-demo-app:
    build: .
    container_name: rest-demo-app
    ports:
      - "8081:8081"
